### ISSUE TITLE
#2: Create a simulation 

### ISSUE THREAD

**Issue by SJ1337** [SJ1337/Th-Bingen#27]
each car knows whether it wants to drive and the road network has a total capacity for cars; implement a single simulation step (which is supposed to represent one hour), where: 

- each individual car announces whether it wants to drive or not
- the network tallies up the number of cars on the road and compares it to its own capacity
-the network decides for each car whether it drives or is delayed due to traffic jams; that decision is based             on how many cars are on the road compared to the network’s capacity: 
 -- less than or equal to capacity ~> all can drive
 --over capacity ~> all are delayed

**Comment by Korkianer** [comment]
@nicolaiparlog 
How to start? Can you give us some hints pls how to start ?

**Comment by nipafx** [comment]
Do the analysis I did in the OOP lectures: Make a list of values and entities and what each of them needs to be able to do in the form of methods.

**Comment by MarcoChrist** [comment]
@nicolaiparlog i have a problem. Theres a error in my pom.xml under <version>${kotlin.version}<version>.
"Kotlin version that is used for building with Maven differs from the one bundled into the IDE plugin"
Nothing is working anymore and i dont know how to fix this problem

**Comment by nipafx** [comment]
#36 @MarcoChrist Please open a new issue for that. Include the exact POM line that shows that error and in IntelliJ, look into _Help_ ~> _About_ and copy the IntelliJ version (a small icon will appear when you enter the overlay with the mouse - click it to copy the entire version kerfuffle).
