### ISSUE TITLE
#2: Release version 2.0

### ISSUE THREAD

**Issue by SJ1337** [SJ1337/Th-Bingen#32]

**Comment by MarcoChrist** [comment]
@nicolaiparlog 
Release 2.0 is released, everything should be fine hopefully 👍

**Comment by nipafx** [comment]
I think you should take this opportunity to check whether everything really works properly, whether you are happy with the tests you've written, and so forth. You can of course start with 3.0 but let me tell you from experience - nothing good comes from rushing.

**Comment by MarcoChrist** [comment]
@nicolaiparlog 
i checked everything and i think it looks quite good. What do you think? Are you checking our stuff from time to time or do you check it later on?

**Comment by nipafx** [comment]
I look at the PRs and occasionally run the code but that's just friendly support. You're responsible for the code. :wink:
