### ISSUE TITLE
Problem with IntelliJ and Kotlin

### ISSUE THREAD

**Issue by MarcoChrist** [SJ1337/Th-Bingen#36]
![pom fehler](https://user-images.githubusercontent.com/28190594/29205964-ff5e006a-7e7f-11e7-90cb-43675e8adaa9.png)

@nicolaiparlog In this screenshot you can see the problem, i dont know what to do about it.

**Comment by MarcoChrist** [comment]
IntelliJ IDEA 2017.2.1
Build #IC-172.3544.35, built on July 31, 2017
JRE: 1.8.0_152-release-915-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by SJ1337** [comment]
found solution, works now
