### ISSUE TITLE
#2: Lower case resource folder

### ISSUE THREAD

**Issue by nipafx** [SJ1337/Th-Bingen#46]
As long as the `Resource` folder starts with capital `R`, the program does not work on Linux. Please fix that.

**Comment by NikMass** [comment]
@nicolaiparlog i tried to fix it and now there are two resources folders. The problem is, if i clone it there is just the one with the capital R.

**Comment by Korkianer** [comment]
@nicolaiparlog 
it seems that windows automatically takes the resources and the Resources folder and creates one out of them because of the name conflict.

**Comment by nipafx** [comment]
There may be two things at play here:

* renaming the folder
* interacting with Git

Renaming a folder on Windows wasn#t strauight forward when you only wanted to change casing. Maybe it helps renaming it from `Resources` to `resourcesXYZ` to `resources`.

When you run `git status` after the rename, it should list the file in the `Resources` folder as deleted and the one in the `resources` folder as untracked. You need to add _both_ to the index to make Git aware of the rename. If you just add the deletion, there will be no folder in Git; if you just add the new one, you will get two. Adding both is easiest with `git add .`. When you run `git status` again, it should tell you that a file was renamed. Then commit, push, PR. :smiley:

**Comment by Korkianer** [comment]
@nicolaiparlog it worked, now its all lower case 😄

**Comment by nipafx** [comment]
Super.
