### ISSUE TITLE
integrate with Travis

### ISSUE THREAD

**Issue by SJ1337** [SJ1337/Th-Bingen#6]

**Comment by MarcoChrist** [comment]
@nicolaiparlog 
Thanks in advance for integrating!

**Comment by nipafx** [comment]
Excuse my German, copy pasted from elsewhere...

Ok... Da dieses Projekt nicht zu einer Organisation gehört, sondern einem User, kann nur der User Travis aktivieren. 😭 Ich kann das nachher konfigurieren, aber anschmeißen muss es @SJ1337.

Dazu bitte Schritte 2 und 3 [aus dieser Anleitung](https://docs.travis-ci.com/user/for-beginners) (natürlich für dieses Projekt hier) durchführen und dann wieder hier Bescheid sagen. Ich bereite solange schonmal die `.travis.yml` vor.

**Comment by SJ1337** [comment]
@nicolaiparlog I finished step 1 and 2, you can now add the .travis.yml file

**Comment by nipafx** [comment]
:+1:
