### ISSUE TITLE
release version 1.0

### ISSUE THREAD

**Issue by SJ1337** [SJ1337/Th-Bingen#9]

**Comment by nipafx** [comment]
Some details on how exactly to make a release once all issues in [the first milestone](https://github.com/SJ1337/Th-Bingen/milestone/2) are done (pardon my German):

* `master` auschecken
* mit `mvn clean install` und `java-jar target/...jar` sicherstellen, dass alles funktioniert
* in der `pom.xml` bei der Version `-SNAPSHOT` entfernen
* nochmal `mvn clean install` und die JAR aus dem `target`-Ordner (beachte, dass `-SNAPSHOT` fehlt) irgendwohin kopieren
* neuen Commit auf `master` mit der Message "Release version 1.0" (oder so)
* den Commit taggen
* in der `pom.xml` die Version `2.0-SNAPSHOT` eintragen
* neuen Commit auf `master` mit der Message "Start work on 2.0" (oder so)
* alles pushen (mit tags)
* auf GitHub das Releases-Menü finden, aus dem Tag ein Release machen und die JAR anhängen:

![attach-binaries](https://user-images.githubusercontent.com/6537432/28945549-47ed17be-78a7-11e7-8eb0-0b358692fc34.png)

**Comment by SJ1337** [comment]
@nicolaiparlog I wanted to create a pull request, I used the command to push but I messed up and merged it

**Comment by nipafx** [comment]
Releases are not done on a branch but on `master` (see step by step instructions above). If you need to reset your `master` to match this repository's `master`, do [this](https://stackoverflow.com/a/1628334/2525313):


```
git fetch upstream
git reset --hard upstream/master
```

That is under the assumption that you have added this repo as remote `upstream` in your local clone. (Your fork should be `origin`.)

**Comment by MarcoChrist** [comment]
@nicolaiparlog  Isnt it possible to just clone everything again and just delete the stuff we dont need?

**Comment by nipafx** [comment]
I'm not sure what exactly you mean by "delete the stuff we dont need".

**Comment by MarcoChrist** [comment]
@nicolaiparlog the Th-Bingen file he merged contains basically the same files. So this is redundant, isnt it?

**Comment by nipafx** [comment]
Ooops, I missed the `Th-Bingen` folder. Yes, that one needs to go, see #33.

**Comment by nipafx** [comment]
Ok, I think you're ready for the release. Whever wants to give it a try, assign the issue to you and follow the steps above one by one. If you have any problems, don't push and ask me here for help.

**Comment by SJ1337** [comment]
@nicolaiparlog We released the Version 1.0
 #pray

**Comment by nipafx** [comment]
:tada: :+1:

**Comment by SJ1337** [comment]
Thx.
